<a href="https://colab.research.google.com/github/Biangelica/Data-Science-MBA-CEMEAI/blob/main/Programa%C3%A7%C3%A3o%20para%20ci%C3%AAncia%20de%20dados/Aula%205/Numpy_II_e_Matplotlib_avaliacao_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color="blue"> MBA em Ciência de Dados</font>
# <font color="blue">Programação para Ciência de Dados</font>

## <font color="blue">Numpy Parte II e Matplotlib - Avaliação</font>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo utiliza corretamente broadcasting para somar o vetor `v` em cada **linha** da matriz `A`, sendo que `v` e `A` são definidos como:
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a) A[:]+v[:]<br>
b) A + v<br>
c) A = A + v.reshape(1,-1)<br>
d) Todas as alternativas estão corretas

In [2]:
A = np.zeros((4,4))
v = np.arange(4)

C = A[:]+v[:]
D = A + v
E = A = A + v.reshape(1,-1)
print(A)

print('C', C)
print('D', D)
print('E', E)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
C [[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
D [[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
E [[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


d) Todas as alternativas estão corretas

Explicação:

A[:]+v[:]: Isso irá somar v a cada linha de A, porque ambos estão sendo fatiados da mesma forma.

A + v: Esta é a forma correta e mais direta de usar broadcasting para somar v a cada linha de A.

A = A + v.reshape(1,-1): Esta opção também está correta. Aqui, você está garantindo que v tenha a forma correta para broadcasting, convertendo-o em um vetor de linha com o reshape(1,-1).

### Exercício 2)
Qual das alternativas explica corretamente como o array `W` está sendo calculado no código abaixo?
```python
u = np.random.randint(0,30,7).reshape(1,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v * u
```

a) `W` é um array unidimensional com 10 elementos, resultado da multiplicação dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) `W` é um array unidimensional com 7 elementos, resultado da multiplicação dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.<br>
c) `W` é um array bidimensional com 7 linhas e 10 colunas, resultado da multiplicação do array `v` com broadcasting em 7 linhas e o array `u` com broadcasting em 10 linhas.<br>
d) `W` é um array bidimensional com 10 linhas e 7 colunas, resultado da multiplicação do array `v` com broadcasting em 7 colunas e do array `u` com broadcasting em 10 linhas.<br>

In [4]:
u = np.random.randint(0,30,7).reshape(1,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v * u
print(u)
print(v)
print(W)

[[ 3  1 13 18 22 27 15]]
[[ 7]
 [29]
 [ 8]
 [21]
 [27]
 [18]
 [18]
 [19]
 [10]
 [16]]
[[ 21   7  91 126 154 189 105]
 [ 87  29 377 522 638 783 435]
 [ 24   8 104 144 176 216 120]
 [ 63  21 273 378 462 567 315]
 [ 81  27 351 486 594 729 405]
 [ 54  18 234 324 396 486 270]
 [ 54  18 234 324 396 486 270]
 [ 57  19 247 342 418 513 285]
 [ 30  10 130 180 220 270 150]
 [ 48  16 208 288 352 432 240]]


d) W é um array bidimensional com 10 linhas e 7 colunas, resultado da multiplicação do array v com broadcasting em 7 colunas e do array u com broadcasting em 10 linhas.

### Exercício 3)
Considere a matriz abaixo. Utilizando redução por soma, encontre o **índice da linha** que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha 6<br>
b) linha 0<br>
c) linha 8<br>
d) linha 9

In [7]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

print('Soma de todos os valores: ', np.sum(A))
print('Soma dos valores das linnhas: ', np.argmax(np.sum(A,axis=1)))

Soma de todos os valores:  421
Soma dos valores das linnhas:  8


c) linha 8

### Exercício 4)
Considerando a matriz `A` do exercício anterior, qual o valor da **maior média** calculada sobre os valores das colunas?

a) 5.8<br>
b) 6.5<br>
c) 3.5<br>
d) 9.1

In [8]:
# Solucao


print('Media por coluna: ',np.max(np.mean(A,axis=0)))

Media por coluna:  6.5


b) 6.5

### Exercício 5)
Suponha que a variável `A` no código abaixo é um array bidimensional com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
b) Substituindo o maior valor de cada linha por -1<br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [9]:
A = np.random.randint(0,30,size=(5,7))

Aargs = np.argsort(A)
print(A)
print(Aargs)

A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
print(A)

[[21  9 10  8 13 25 25]
 [20  0 14  5 19 12 16]
 [21  0 24  7 24 23  1]
 [ 9 15 26 26  5  4  5]
 [ 1 19 28 26 11 28 21]]
[[3 1 2 4 0 5 6]
 [1 3 5 2 6 4 0]
 [1 6 3 0 5 2 4]
 [5 4 6 0 1 2 3]
 [0 4 1 6 3 2 5]]
[[21  9 10  8 13 25 -1]
 [-1  0 14  5 19 12 16]
 [21  0 24  7 -1 23  1]
 [ 9 15 26 -1  5  4  5]
 [ 1 19 28 26 11 -1 21]]


b) Substituindo o maior valor de cada linha por -1