<a href="https://colab.research.google.com/github/Biangelica/Data-Science-MBA-CEMEAI/blob/main/Programa%C3%A7%C3%A3o%20para%20ci%C3%AAncia%20de%20dados/Aula%204/Numpy_I_avaliacao_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

## <font color='red'> As respostas da avaliação devem ser inseridas no moodle </font>

In [ ]:
import numpy as np

### Exercício 1)
Considere o array `X` como descrito abaixo:
```python
[[0  1  2  3  4]
 [5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
```
Qual dos códigos abaixo imprime um array com os elementos 13, 18 e 6 a partir de `X`?

a) print(X[1,2,3])<br>
b) print(X[[2,3,1],[3,3,1]])</font> <br>
c) print(X[:,[2,3,1])<br>
d) print([1,2,3],:)

In [ ]:
X=np.array([[0,  1,  2,  3,  4],
            [5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19]])

print(X[[2,3,1],[3,3,1]])

[13 18  6]


### Exercício 2)
Considerando o array `X` do exercício 1). Qual alternativa descreve corretamente a construção de `Y` no código abaixo?
```python
Y = X[1:3,[0,2,3]]
```

a) `Y` é uma _cópia_ dos elementos das linhas 1 e 2 e colunas 0,2 e 3 de `X`<br>
b) `Y` é uma _view_ dos elementos das linhas 1 e 2 e colunas 0,2 e 3 de `X`<br>
c) `Y` é uma _cópia_ dos elementos das linhas 1,2 e 3 e colunas 0,2 e 3 de `X`<br>
d) `Y` é uma _view_ dos elementos das linhas 1,2 e 3 e colunas 0,2 e 3 de `X`

In [ ]:
Y = X[1:3,[0,2,3]]


print(Y)
print('--------')
print(X)


[[ 5  7  8]
 [10 12 13]]
--------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


b) Y é uma view dos elementos das linhas 1 e 2 e colunas 0, 2 e 3 de X

Isso porque ao fazer a seleção com X[1:3, [0, 2, 3]], você está selecionando um slice das linhas 1 e 2 e das colunas 0, 2 e 3 de X. Essa operação retorna uma view dos elementos selecionados em X, não uma cópia.


No NumPy, quando você usa a notação de slicing 1:3 em um array bidimensional como X, isso seleciona as linhas começando da linha de índice 1 (inclusive) até a linha de índice 3 (exclusive). Portanto, no caso de X[1:3, [0, 2, 3]], você está selecionando as linhas de índice 1 e 2, e as colunas de índice 0, 2 e 3.

Esse é um comportamento padrão do slicing em Python e em muitas bibliotecas que trabalham com arrays multidimensionais, incluindo o NumPy. O intervalo é sempre do primeiro índice inclusivo até o segundo índice exclusivo. Por isso, ao usar 1:3, você está selecionando as linhas 1 e 2.

### Exercício 3)
Considere o numpy array `A` abaixo:
```python
[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]
```
Qual das alternativas abaixo corresponde ao número de dimensões (ndim), a forma (shape) e ao número de elementos (size) no array, respectivamente?

a) (5, 6) 2 2<br>
b) 2 (5, 6) 2<br>
c) (5, 6) 2 30<br>
d) 2 (5, 6) 30

In [ ]:
A = np.array([[ 2, 19, 16,  1, 12,  7],
 [ 5, 19, 18, 17,  9,  3],
 [16,  4, 18, 11,  4,  2],
 [ 6,  2, 18, 14, 15, 15],
 [ 4,  8,  1, 14, 19, 13]])

print('A.shape = ',A.shape)
print('A.ndim = ',A.ndim)
print('A.size =',A.size)

A.shape =  (5, 6)
A.ndim =  2
A.size = 30


c) (5, 6) 2 30

### Exercício 4)
Considere o numpy array `A` do exercício 3). Escreva um código para criar uma máscara para selecionar todos os elementos pares do array e armazena-los em um novo array *unidimensional* `B`. O resultado do comando
```python
print(B.size)
```
será:<br>
a) 13<br>
b) 15<br>
c) 16<br>
d) 17

In [ ]:
B = (A%2 == 0)

print(A[B])

print(A[B].size)

[ 2 16 12 18 16  4 18  4  2  6  2 18 14  4  8 14]
16


In [ ]:
#Solucao


### Exercício 5)
Ainda considerando o array `A` do exercício 3), que alternativa melhor explica o que o código abaixo está realizando:
```python
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```
a) insere elementos -1 nas linhas e colunas ímpares de `A` utilizando uma máscara booleana<br>
b) insere elementos -1 nas posições com índices ímpares (linha e coluna) de `A` utilizando uma máscara booleana<br>
c) insere elementos -1 nas linhas com índices ímpares e colunas pares de `A` utilizando uma máscara booleana<br>
d) troca os elementos impares da matriz por -1 utilizando uma máscara booleana

In [ ]:
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
print(A)

[[ 2 19 16  1 12  7]
 [ 5 -1 18 -1  9 -1]
 [16  4 18 11  4  2]
 [ 6 -1 18 -1 15 -1]
 [ 4  8  1 14 19 13]]


b) insere elementos -1 nas posições com índices ímpares (linha e coluna) de A utilizando uma máscara booleana

Isso porque o código cria uma máscara booleana que identifica as posições com índices ímpares (tanto de linha quanto de coluna) na matriz A. Em seguida, ele usa essa máscara para atribuir o valor -1 nessas posições específicas.